main: com.characterlim.voidpit.VoidPitPlugin
name: VoidPit
version: 0.1
author: characterlim
description: Toss items into the Void Pit to reach a community goal!
commands:
  pit:
    description: The command for all things related to the Void Pit
    permission: voidpit.pit
    permission-message: You don't have permission to use this command!